/**
 * Bundled list of frequently impersonated brands and their legitimate
 * registrable domains. Used for typosquat distance, brand-in-subdomain
 * detection, and brand-keyword/off-brand-domain pairing.
 *
 * This ships a curated high-value subset; extend BRAND_DOMAINS to grow
 * coverage (the heuristics scale linearly and are run off the hot path).
 */
export interface Brand {
  /** Brand keyword as it appears in page text/titles (lowercase). */
  name: string;
  /** Legitimate registrable domains for this brand. */
  domains: string[];
}

export const BRANDS: Brand[] = [
  { name: 'paypal', domains: ['paypal.com', 'paypal.me'] },
  { name: 'google', domains: ['google.com', 'goo.gl', 'withgoogle.com', 'google.co.uk'] },
  { name: 'gmail', domains: ['gmail.com', 'google.com'] },
  { name: 'microsoft', domains: ['microsoft.com', 'microsoftonline.com', 'live.com', 'office.com', 'azure.com'] },
  { name: 'outlook', domains: ['outlook.com', 'live.com', 'office.com', 'microsoft.com'] },
  { name: 'office 365', domains: ['office.com', 'microsoft.com', 'microsoftonline.com'] },
  { name: 'apple', domains: ['apple.com', 'icloud.com'] },
  { name: 'icloud', domains: ['icloud.com', 'apple.com'] },
  { name: 'amazon', domains: ['amazon.com', 'amazon.co.uk', 'amazon.de', 'amazon.in', 'aws.amazon.com'] },
  { name: 'facebook', domains: ['facebook.com', 'fb.com', 'meta.com'] },
  { name: 'instagram', domains: ['instagram.com'] },
  { name: 'whatsapp', domains: ['whatsapp.com', 'wa.me'] },
  { name: 'netflix', domains: ['netflix.com'] },
  { name: 'linkedin', domains: ['linkedin.com'] },
  { name: 'twitter', domains: ['twitter.com', 'x.com'] },
  { name: 'dropbox', domains: ['dropbox.com'] },
  { name: 'adobe', domains: ['adobe.com'] },
  { name: 'docusign', domains: ['docusign.com', 'docusign.net'] },
  { name: 'chase', domains: ['chase.com'] },
  { name: 'wells fargo', domains: ['wellsfargo.com'] },
  { name: 'bank of america', domains: ['bankofamerica.com'] },
  { name: 'citibank', domains: ['citi.com', 'citibank.com'] },
  { name: 'hsbc', domains: ['hsbc.com', 'hsbc.co.uk'] },
  { name: 'barclays', domains: ['barclays.co.uk', 'barclays.com'] },
  { name: 'santander', domains: ['santander.com', 'santander.co.uk'] },
  { name: 'american express', domains: ['americanexpress.com'] },
  { name: 'amex', domains: ['americanexpress.com'] },
  { name: 'visa', domains: ['visa.com'] },
  { name: 'mastercard', domains: ['mastercard.com'] },
  { name: 'venmo', domains: ['venmo.com'] },
  { name: 'zelle', domains: ['zellepay.com'] },
  { name: 'cash app', domains: ['cash.app'] },
  { name: 'coinbase', domains: ['coinbase.com'] },
  { name: 'binance', domains: ['binance.com'] },
  { name: 'kraken', domains: ['kraken.com'] },
  { name: 'metamask', domains: ['metamask.io'] },
  { name: 'ledger', domains: ['ledger.com'] },
  { name: 'trezor', domains: ['trezor.io'] },
  { name: 'blockchain', domains: ['blockchain.com'] },
  { name: 'steam', domains: ['steampowered.com', 'steamcommunity.com'] },
  { name: 'epic games', domains: ['epicgames.com'] },
  { name: 'roblox', domains: ['roblox.com'] },
  { name: 'discord', domains: ['discord.com', 'discord.gg'] },
  { name: 'telegram', domains: ['telegram.org', 't.me'] },
  { name: 'spotify', domains: ['spotify.com'] },
  { name: 'ebay', domains: ['ebay.com', 'ebay.co.uk'] },
  { name: 'alibaba', domains: ['alibaba.com'] },
  { name: 'aliexpress', domains: ['aliexpress.com'] },
  { name: 'walmart', domains: ['walmart.com'] },
  { name: 'costco', domains: ['costco.com'] },
  { name: 'target', domains: ['target.com'] },
  { name: 'usps', domains: ['usps.com'] },
  { name: 'ups', domains: ['ups.com'] },
  { name: 'fedex', domains: ['fedex.com'] },
  { name: 'dhl', domains: ['dhl.com', 'dhl.de'] },
  { name: 'royal mail', domains: ['royalmail.com'] },
  { name: 'irs', domains: ['irs.gov'] },
  { name: 'hmrc', domains: ['gov.uk'] },
  { name: 'social security', domains: ['ssa.gov'] },
  { name: 'netsuite', domains: ['netsuite.com'] },
  { name: 'salesforce', domains: ['salesforce.com', 'force.com'] },
  { name: 'okta', domains: ['okta.com'] },
  { name: 'duo', domains: ['duosecurity.com', 'duo.com'] },
  { name: 'onelogin', domains: ['onelogin.com'] },
  { name: 'zoom', domains: ['zoom.us', 'zoom.com'] },
  { name: 'slack', domains: ['slack.com'] },
  { name: 'github', domains: ['github.com'] },
  { name: 'gitlab', domains: ['gitlab.com'] },
  { name: 'atlassian', domains: ['atlassian.com', 'atlassian.net'] },
  { name: 'yahoo', domains: ['yahoo.com', 'yahoo.co.jp'] },
  { name: 'aol', domains: ['aol.com'] },
  { name: 'comcast', domains: ['comcast.com', 'xfinity.com'] },
  { name: 'xfinity', domains: ['xfinity.com'] },
  { name: 'verizon', domains: ['verizon.com'] },
  { name: 'at&t', domains: ['att.com'] },
  { name: 't-mobile', domains: ['t-mobile.com'] },
  { name: 'vodafone', domains: ['vodafone.com', 'vodafone.co.uk'] },
  { name: 'orange', domains: ['orange.fr', 'orange.com'] },
  { name: 'airbnb', domains: ['airbnb.com'] },
  { name: 'booking', domains: ['booking.com'] },
  { name: 'uber', domains: ['uber.com'] },
  { name: 'lyft', domains: ['lyft.com'] },
  { name: 'doordash', domains: ['doordash.com'] },
  { name: 'shopify', domains: ['shopify.com', 'myshopify.com'] },
  { name: 'stripe', domains: ['stripe.com'] },
  { name: 'square', domains: ['squareup.com', 'square.com'] },
  { name: 'intuit', domains: ['intuit.com'] },
  { name: 'turbotax', domains: ['turbotax.intuit.com', 'intuit.com'] },
  { name: 'quickbooks', domains: ['quickbooks.intuit.com', 'intuit.com'] },
  { name: 'robinhood', domains: ['robinhood.com'] },
  { name: 'fidelity', domains: ['fidelity.com'] },
  { name: 'vanguard', domains: ['vanguard.com'] },
  { name: 'schwab', domains: ['schwab.com'] },
  { name: 'capital one', domains: ['capitalone.com'] },
  { name: 'discover', domains: ['discover.com'] },
  { name: 'usaa', domains: ['usaa.com'] },
  { name: 'navy federal', domains: ['navyfederal.org'] },
  { name: 'norton', domains: ['norton.com'] },
  { name: 'mcafee', domains: ['mcafee.com'] },
  { name: 'geek squad', domains: ['bestbuy.com'] },
  { name: 'best buy', domains: ['bestbuy.com'] },
  { name: 'onedrive', domains: ['onedrive.live.com', 'live.com', 'microsoft.com'] },
  { name: 'sharepoint', domains: ['sharepoint.com', 'microsoft.com'] },
  { name: 'icici', domains: ['icicibank.com'] },
  { name: 'hdfc', domains: ['hdfcbank.com'] },
  { name: 'sbi', domains: ['onlinesbi.sbi', 'sbi.co.in'] },
  { name: 'commbank', domains: ['commbank.com.au'] },
  { name: 'westpac', domains: ['westpac.com.au'] },
  { name: 'anz', domains: ['anz.com.au', 'anz.com'] },
  { name: 'nab', domains: ['nab.com.au'] },
  { name: 'deutsche bank', domains: ['db.com', 'deutsche-bank.de'] },
  { name: 'sparkasse', domains: ['sparkasse.de'] },
  { name: 'ing', domains: ['ing.com', 'ing.nl', 'ing.de'] },
  { name: 'rabobank', domains: ['rabobank.nl'] },
  { name: 'bnp paribas', domains: ['bnpparibas.com'] },
  { name: 'credit agricole', domains: ['credit-agricole.fr'] },
  { name: 'la poste', domains: ['laposte.fr'] },
  { name: 'caixa', domains: ['caixa.gov.br', 'caixabank.es'] },
  { name: 'itau', domains: ['itau.com.br'] },
  { name: 'bradesco', domains: ['bradesco.com.br'] },
  { name: 'mercado libre', domains: ['mercadolibre.com', 'mercadolivre.com.br'] },
  { name: 'rakuten', domains: ['rakuten.co.jp', 'rakuten.com'] },
  { name: 'line', domains: ['line.me'] },
  { name: 'kakao', domains: ['kakao.com'] },
  { name: 'naver', domains: ['naver.com'] },
];

/** All legitimate brand domains, flattened, for quick membership checks. */
export const BRAND_DOMAIN_SET: ReadonlySet<string> = new Set(
  BRANDS.flatMap((b) => b.domains),
);

/** Second-level labels of brand domains (e.g. "paypal" from paypal.com). */
export const BRAND_SLD_SET: ReadonlySet<string> = new Set(
  BRANDS.flatMap((b) => b.domains.map((d) => d.split('.')[0]!)),
);
